# http://docs.openstack.org/developer/heat/template_guide/hot_spec.html#heat-template-version
heat_template_version: 2014-10-16


description: >
  NeCTAR Sample Template showing the creation of a user and their aws access keys by heat.


resources:

  # http://docs.openstack.org/developer/heat/template_guide/cfn.html#AWS::IAM::User
  cfn_user:
    type: AWS::IAM::User

  # http://docs.openstack.org/developer/heat/template_guide/cfn.html#AWS::IAM::AccessKey
  web_server_access_key:
    type: AWS::IAM::AccessKey
    properties:
      UserName: { get_resource:  cfn_user }


outputs:

  access_key:
    value: { get_resource:  web_server_access_key }
    description: "The access key"

  secret_access_key:
    value: { get_attr: [ web_server_access_key, SecretAccessKey ] }
    description: "The secret access key"

  user_name:
    value: { get_attr: [ web_server_access_key, UserName ] }
    description: "The username associated with the access key"