# http://docs.openstack.org/developer/heat/template_guide/hot_spec.html#heat-template-version
heat_template_version: 2014-10-16


description: >
  NeCTAR sample template that shows the differences between an OpenStack and an AWS instance type


parameters:

  key_name:
    type: string
    description:
      Name of an existing key pair to enable SSH access to the instances.

  image_id:
    type: string
    description: ID of the image to use for the instance to be created
    default: 'fc48b5bb-e67d-4e39-b9ba-b6725c8b0c88'


resources:

  # http://docs.openstack.org/developer/heat/template_guide/cfn.html#AWS::EC2::Instance
  aws_instance:
    type: AWS::EC2::Instance
    properties:
      ImageId: { get_param: image_id}
      InstanceType: m2.tiny
      KeyName: { get_param: key_name }

  # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Nova::Server
  nova_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id}
      flavor: m2.tiny
      key_name: { get_param: key_name }


outputs:

  aws_instance_ip:
    description: Public IP address of the newly created AWS style instance.
    value:
      str_replace:
        template: ssh ec2_user@host -i ~/.ssh/key.pem
        params:
          host: { get_attr: [aws_instance, PublicIp] }
          key: { get_param: key_name }

  nova_instance_ip:
    description: Public IP address of the newly created HOT style instance.
    value:
      str_replace:
        template: ssh ec2_user@host -i ~/.ssh/key.pem
        params:
          host: { get_attr: [nova_instance, first_address] }
          key: { get_param: key_name }

