# http://docs.openstack.org/developer/heat/template_guide/hot_spec.html#heat-template-version
heat_template_version: 2014-10-16


description: >
  NeCTAR Sample Template - A very simple one that just fires up an instance using the OS::Nova::KeyPair
  resource type configured to use an existing public key that you have on your machine. You will have to
  paste the contents of the key into the public_key_value parameter. Then ssh into the instance
  using the private half of the keypair...


parameters:

  public_key_name:
    type: string
    description: The name of your public key you are providing

  public_key_value:
    type: string
    description: The actual public key you are providing

  instance_type:
    type: string
    description: The NeCTAR flavour the webserver is to run on
    default: m2.xsmall
    # can use the provided custom constraint to check that the flavor does exist
    constraints:
      - custom_constraint: nova.flavor
        description: Must be a valid NeCTAR flavour

  image_id:
    type: string
    description: ID of the image to use for the instance to be created
    default: fc48b5bb-e67d-4e39-b9ba-b6725c8b0c88


resources:

  # This key pair must already exist
  existing_key_pair:
    # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Nova::KeyPair
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: public_key_name }
      public_key:  { get_param: public_key_value }

  instance:
    # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Nova::Server
    type: OS::Nova::Server
    properties:
      key_name: { get_resource: existing_key_pair }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      image_update_policy: REPLACE
      user_data_format: RAW

outputs:

  instance_ip:
    description: The IP address of instance one
    value: { get_attr: [instance, first_address] }
