# http://docs.openstack.org/developer/heat/template_guide/hot_spec.html#heat-template-version
heat_template_version: 2014-10-16


parameters:

  key_name:
    type: string
    description: Name of an existing KeyPair to enable SSH access to instance two
    constraints:
      - custom_constraint: nova.keypair

  instance_type:
    type: string
    description: The NeCTAR flavour the webserver is to run on
    default: m2.xsmall
    constraints:
      - allowed_values: [m2.xsmall, m2.small, m1.small]
        description:
          Must be a valid NeCTAR flavour, limited to the smaller ones available

  image_id:
    type: string
    description: ID of the image to use for the instance to be created
    default: 7313d773-3cd9-4e69-98d2-eff1f9797480


resources:

  policy_group:
    # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Nova::ServerGroup
    type: OS::Nova::ServerGroup
    # A Nova ServerGroup
    properties:
      name: nova-server-group
      # see http://dev.cloudwatt.com/en/blog/affinity-and-anti-affinity-in-openstack.html
      # policies: [affinity]


  # If we uncomment the scheduler_hints, this template will fail:
  # This appears to be due to a bug in nova.
  auto_scaling_group:
    # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Heat::AutoScalingGroup
    type: OS::Heat::AutoScalingGroup
    properties:
      resource:
        type: OS::Nova::Server
        properties:
            key_name: { get_param: key_name }
            image: { get_param: image_id }
            flavor: { get_param: instance_type }
            #scheduler_hints: { group: { get_resource: policy_group }}
      min_size: 1
      desired_capacity: 3
      max_size: 5

  scale_up_policy:
    # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Heat::ScalingPolicy
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: auto_scaling_group }
      cooldown: 60
      scaling_adjustment: 1

  scale_down_policy:
    # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Heat::ScalingPolicy
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: auto_scaling_group }
      cooldown: 60
      scaling_adjustment: '-1'


outputs:

  scale_up_url:
    description: >
      This URL is the webhook to scale the group up. Invoke by doing an HTTP POST to this URL.
      No body or other headers is needed. But do put quotes around the url!
    value: { get_attr: [scale_up_policy, alarm_url] }

  scale_down_url:
    description: >
      This URL is the webhook to scale the group down. Invoke by doing an HTTP POST to this URL.
      No body or other headers is needed. But do put quotes around the url
    value: { get_attr: [scale_down_policy, alarm_url] }