# http://docs.openstack.org/developer/heat/template_guide/hot_spec.html#heat-template-version
heat_template_version: 2014-10-16

# Fails on the NeCTAR cloud with ERROR: Unknown resource Type : OS::Heat::Stack
# This is because it was only introduced in kilo

description: >
  basic_instance.yaml is a template that fires up a single instance. This template is supposed to fire up two copies,
  however, until neutron support is enabled, it will fail :(

parameters:

  key_name:
    type: string
    description: Name of an existing KeyPair to enable SSH access to the instances
    constraints:
      - custom_constraint: nova.keypair

  instance_type:
    type: string
    description: The NeCTAR flavour the webserver is to run on
    default: m2.xsmall
    constraints:
      - allowed_values: [m2.xsmall, m2.small, m1.small]
        description:
          Must be a valid NeCTAR flavour, limited to the smaller ones available
      - custom_constraint: nova.flavor

  image_id:
    type: string
    description: ID of the image to use for the instance to be created
    default: fc48b5bb-e67d-4e39-b9ba-b6725c8b0c88
    constraints:
      - custom_constraint: glance.image


resources:

  stack_one:
    # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Heat::Stack
    type: OS::Heat::Stack
    properties:
      template: { get_file: "https://raw.githubusercontent.com/NeCTAR-RC/heat-templates/master/juno/basic_instance.yaml" }
      timeout: 60
      parameters:
        key_name: { get_param: key_name }
        image_id: { get_param: image_id }
        instance_type: { get_param: instance_type }

  stack_two:
    # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Heat::Stack
    type: OS::Heat::Stack
    properties:
      template: { get_file: "https://raw.githubusercontent.com/NeCTAR-RC/heat-templates/master/juno/basic_instance.yaml" }
      timeout: 60
      parameters:
        key_name: { get_param: key_name }
        image_id: { get_param: image_id }
        instance_type: { get_param: instance_type }


outputs:

  stack_one_outputs:
    description: Output of stack_one.
    value: { get_attr: [stack_one, outputs] }

  stack_two_outputs:
    description: Output of stack_two.
    value: { get_attr: [stack_two, outputs] }
