HeatTemplateFormatVersion: '2012-12-12'

Description: 'NeCTAR Sample Template
  Just a simple template to install Apache on a single Ubuntu instance.'

Parameters:
  # First off, the parameters that affect the environment
  KeyName: {Description: Name of an existing KeyPair
      to enable SSH access to the instances, Type: String}
  InstanceType:
    Description: The NeCTAR flavour the webserver is to run on
    Type: String
    Default: m1.small
    AllowedValues: [m1.small, m1.medium, m1.large, m1.xlarge, m1.xxlarge]
    ConstraintDescription: must be a valid NeCTAR flavour.

Resources:
  ApacheServer:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            apt:
              apache2: []
          services:
            systemd:
              apache2: {enabled: 'true', ensureRunning: 'true'}
    Properties:
      # the following is currently the only ubuntu image with heat-cfntools installed
      ImageId: 6464e3f6-3e39-4b78-811f-de6511b42585
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
      # the following are project specific, and will have to be adjusted.
      SecurityGroups: [default, webserver]
      # the following is written to /var/lib/cloud/data/cfn-userdata
      # note the call to cfn-init which causes the AWS::CloudFomration::Init to be actioned
      UserData: |
        #!/bin/bash -v
        /usr/local/bin/cfn-init

Outputs:
  WebsiteURL:
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt: [ApacheServer, PublicIp]
        - /
    Description: URL for Apache server

