HeatTemplateFormatVersion: '2012-12-12'


Description: 'NeCTAR Sample Template - one of the simplest possible. It just fires up an instance of ubuntu'


Parameters:

  KeyName:
    Description: Name of an existing KeyPair to enable SSH access to the instances
    Type: String

  InstanceType:
    Description: The NeCTAR flavour the webserver is to run on
    Type: String
    Default: m1.small
    AllowedValues: [m1.small, m1.medium, m1.large, m1.xlarge, m1.xxlarge]
    ConstraintDescription: This must be a valid NeCTAR flavour.


Resources:

  ApacheServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 884bfe1b-1c87-4a34-88da-69447b0ab8c6
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
      # the following are project specific, and will have to be adjusted.
      SecurityGroups: [default]


Outputs:

  WebsiteURL:
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt: [ApacheServer, PublicIp]
        - /
    Description: URL for Apache server