HeatTemplateFormatVersion: '2012-12-12'

Description: "Template to show Swift via S3 in action"

# If you upload the file index.html into the resultant container, naming it 'index.html',
# and the output url will return it.
# However, if you forget to delete index.html from the container before you delete the stack,
# the container will remain behind. A bug, a feature or a safeguard?

Resources:
  S3ContainerWebsite:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    Properties:
      AccessControl: "PublicRead"
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "error.html"

Outputs:
  indexURL:
    Description: "URL for index page hosted on S3"
    Value:
      Fn::Replace:
      - the_url: {'Fn::GetAtt': [S3ContainerWebsite, WebsiteURL]}
      - the_url/index.html
  DomainName:
    Description: "Domain of S3 bucket"
    Value:
      Fn::GetAtt:
        - "S3ContainerWebsite"
        - "DomainName"
