# Juno Release
heat_template_version: 2014-10-16

description: 'Install a basic Ubuntu server. '

parameters:

  key_name:
    type: string
    label: Key Name
    description: Name of an existing KeyPair to enable SSH access to the instances. 
    
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    default: ubuntu-12.04
    constraints:
        - allowed_values: [ ubuntu-12.04, ubuntu-12.10, ubuntu-13.10 ]
          description: Value must be one of ubuntu-12.04, ubuntu-12.10, ubuntu-13.10.
    
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used. 
    default: m1.small
    constraints:
        - allowed_values: [ m1.small, m1.medium, m1.large, m1.xlarge ]
          description: Value must be one of m1.small, m1.medium, m1.large or m1.xlarge.

resources:

  basic_server:
        type: OS::Nova::Server
        properties:
            key_name: { get_param: key_name }
            image: 
                "Fn::Select":
                    - { get_param: image_id }
                    -   
                        "ubuntu-12.04": "884bfe1b-1c87-4a34-88da-69447b0ab8c6"
                        # TODO: following image doesn't work properly yet
                        "ubuntu-12.10": "50807835-eadf-4692-92e0-1b1ecc1cdfad"
                        # TODO: following image doesn't work properly yet.
                        "ubuntu-13.10": "31c3848c-4d88-4e94-99cc-1e8e77c2c8cf"
            flavor: { get_param: instance_type }
    
outputs:
    instance_ip:
        description: The IP address of the deployed instance
        value: { get_attr: [basic_server, first_address] }
